---
title: "Example: Saskatchewan"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example: Saskatchewan}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment  = "#>",
  message  = FALSE, 
  results  = "hide", 
  fig.show = "hide",
  eval     = FALSE
)
```

```{r setup}
library(CBM4r)
```

## Getting started

### Initialize the CBM4 virtual environment

```{r use_virtualeenv}
# Use the CBM4 virtual environment
# See `vignette("Getting-started", package = "CBM4r")`
reticulate::use_virtualenv("r-CBM4")
```

### Set inputs

```{r inputs}
# Set input test data directory
testdata <- system.file(file.path("testdata", "SK"), package = "CBM4r")

# Read study area grid
grid_rast <- do.call(terra::rast, data.table::fread(file.path(testdata, "grid_rast.csv")))

# Read cohort data and cohort classifier columns
cohorts     <- data.table::fread(file.path(testdata, "cohorts.csv"))
classifiers <- readLines(file.path(testdata, "classifiers.txt"))

# Read growth curve metadata and carbon increments
gc_meta <- data.table::fread(file.path(testdata, "gc_meta.csv"))
gc_incr <- data.table::fread(file.path(testdata, "gc_incr.csv"))

# Read disturbance metadata and events
dist_meta   <- data.table::fread(file.path(testdata, "dist_meta.csv"))
dist_events <- data.table::fread(file.path(testdata, "dist_events.csv"))
```

## Simulate with CBM4

### Set output path

```{r paths}
# Set CBM4 output data directory path
cbm4_data <- "cbm4_data"
```

### Set study area metadata

```{r grid_meta}
# Set study area metadata
grid_meta <- cbm4_grid_meta(
  grid_rast       =  grid_rast,
  admin_boundary  = "Saskatchewan",
  eco_boundary_id = 6
)

# Alternatively: set grid metadata in an existing pixels table
grid_meta <- data.table::data.table(
  pixel_index     = 1:terra::ncell(grid_rast),
  admin_boundary  = "Saskatchewan",
  eco_boundary_id = 6
)
cbm4_set_grid_meta(grid_meta, grid_rast = grid_rast)
```

### Run spinup

```{r spinup}
# Write inventory to CBM4 data directory
cbm4_write_inventory(
  cbm4_data,
  grid_meta   = grid_meta,
  grid_rast   = grid_rast,
  cohorts     = cohorts,
  classifiers = classifiers
)

# Write spinup parameters to CBM4 data directory
cbm4_write_spinup_parameters(
  cbm4_data,
  gc_meta = gc_meta,
  gc_incr = gc_incr
)

# Run CBM4 spinup
cbm4_spinup(cbm4_data)

```

### Run annual steps

```{r step}
# Write step parameters to CBM4 data directory
cbm4_write_step_parameters(
  cbm4_data,
  gc_meta = gc_meta,
  gc_incr = gc_incr
)

# Write disturbances to CBM4 data directory
cbm4_write_disturbance(
  cbm4_data,
  dist_meta   = dist_meta,
  dist_events = dist_events
)

# Run annual step for year 1
cbm4_step(cbm4_data, timestep = 1)

# Run annual step for year 2
cbm4_step(cbm4_data, timestep = 2)
```

